### PR TITLE
Added a support of adding a UITextField to the alert controller.

### PR DESCRIPTION
**Pull request by owlcoding**

### CODE REVIEW

**Comment by The0racle** [comment]
+1

**Comment by Codeido** [comment]
This weekend I will look at this pull request.

**Comment by fedmeloni** [comment]
Sorry @Codeido , what about this pull request?

**Comment by Codeido** [comment]
Hi @owlcoding, thanks for this pull request and sorry for the delay.

I reviewed the pull request, and the principle around the implementation is ok, but there are some problems. For example, when i select a text field and the keyboard appear, the text field go under the keyboard. In this way, i can't close the keyboard and i can't see what i wrote on the textfield.

If you implement this part, i can merge your pull request ;)

simulator screen shot 27 dic 2016 14 00 00

**Comment by Codeido** [comment]
Merged. Thanks to @klauslanza for the fix. https://github.com/Codeido/PMAlertController/pull/34

**Comment by klauslanza** [comment]
Thanks @Codeido and thanks to @fedmeloni for the kickstart :-)

**Pull request merged**
