### PR TITLE
add Carthage to .gitignore

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by Codeido** [comment]
Hi @AndrewSB, can you explain to me this pull request? Thanks

**Comment by AndrewSB** [comment]
Yeah! I use `carthage` as my dependency manager to pull down `PMAlertController`, and I use `Carthage`'s `--use-submodules` flag.

That leads to `PMAlertController`'s submodule having "`untracked content`": i.e. the Carthage folder that `carthage --use-submodules` embeds into the `PMAlertController/`dir.

This PR makes it so my submodule for PMAlertController will not be dirty, with untracked content

**Comment by Codeido** [comment]
Sorry for the delay @AndrewSB.

You agree with me that would be the case that this step might be done by the developer on the single project inside his file gitignore?

**Comment by AndrewSB** [comment]
I wouldn't say it's stupid, submodules are tricky. As far as I know, there's no user configurable way to solve the problem (without forking this library). I can gitignore Carthage for my git project, but the submodule ignores the parent gitignore since it has its own

**Comment by Codeido** [comment]
Thanks for the explanation ;) merged

**Pull request merged**
